### ISSUE TITLE
demucs_mt.cpp.main hard wired for 4-source

### ISSUE THREAD

**Issue by unruhschuh** [sevagh/demucs.cpp#15]
The multithreaded cli seems to be hard wired for 4-source models as you can see in this for loop:
https://github.com/sevagh/demucs.cpp/blob/6f0eba0e200b78cb0bbbc6ffcdbfafc0a6d8272b/cli-apps/threaded_inference.hpp#L141

**Comment by sevagh** [comment]
Seems like a typo, let me double check. Want to make a PR?

**Comment by sevagh** [comment]
Fixed in https://github.com/sevagh/demucs.cpp/commit/88b0dbbbcbf42b47d70dbb7a2ac0d87082161cb2
