### ISSUE TITLE
Memory access error with MT on mac

### ISSUE THREAD

**Issue by opchronatron** [sevagh/demucs.cpp#18]
seems to be in the layer_norm

./build/demucs_ft_mt.cpp.main ./ggml-demucs/

DRUMS    [THREAD 1] (9.615%) Time encoder 2
DRUMS    [THREAD 3] (11.538%) Freq encoder 2
DRUMS    [THREAD 3] (13.462%) Time encoder 3
DRUMS    [THREAD 3] (15.385%) Freq encoder 3
DRUMS    [THREAD 0] (11.538%) Freq encoder 2
DRUMS    [THREAD 3] (15.385%) Applying crosstransformer
zsh: segmentation fault  ./build/demucs_ft_mt.cpp.main ./ggml-demucs/ 

using lldb to watch it

RUMS    [THREAD 3] (9.615%) Time encoder 2
DRUMS    [THREAD 1] (15.385%) Freq encoder 3
DRUMS    [THREAD 1] (15.385%) Applying crosstransformer
Process 85078 stopped
* thread #22, stop reason = EXC_BAD_ACCESS (code=1, address=0x8)
    frame #0: 0x0000000111c361b0 libdemucs_ft_mt_python.dylib`demucscpp::layer_norm(Eigen::Tensor<float, 3, 0, long> const&, Eigen::Tensor<float, 1, 0, long> const&, Eigen::Tensor<float, 1, 0, long> const&, float) + 832
libdemucs_ft_mt_python.dylib`demucscpp::layer_norm:
->  0x111c361b0 <+832>: ldr    x8, [x8]
    0x111c361b4 <+836>: ldr    x9, [x9]
    0x111c361b8 <+840>: ldp    x13, x14, [x19]
    0x111c361bc <+844>: ldr    x15, [x19, #0x10]
Target 0: (Python) stopped.

**Comment by opchronatron** [comment]
im dumb.. did not export all the weights

**Comment by sevagh** [comment]
I should probably better handle the case where the models didn't load correctly.
