### ISSUE TITLE
Amount of time to demux an audio file

### ISSUE THREAD

**Issue by husnoo** [sevagh/demucs.cpp#2]
Hi, do you know roughly how long it takes for you to demux an audio file? I've tried with a clip that's 1m30s long, and it took 10m43, so x7 times as long. Is this expected, or have I done something silly?

$ cat /proc/cpuinfo  | grep "model name" | head -n1
model name      : Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz

(used the 4 sources model).

Thanks!

**Comment by sevagh** [comment]
On my computer (AMD Ryzen 5950X processor), it takes ~34 seconds to demix a 5-second test track (with OMP_NUM_THREADS=1). That seems to line up with your measurement, 7x demixing time compared to track length

Note that demucs.cpp was designed to use the demucs segment length of 7.8 seconds (that might explain where the 7 number comes from):
* https://github.com/sevagh/demucs.cpp/blob/main/src/model.hpp#L669
* https://github.com/sevagh/demucs.cpp/blob/main/src/model.hpp#L19

**Comment by husnoo** [comment]
Thanks! I was able to run it on a 3090, it's much faster now!

**Comment by sevagh** [comment]
Nice, how? Did you use NVBLAS/cuBLAS? Or the proper PyTorch version of Demucs?

I also have a 3090 but I don't target any GPU acceleration in the demucs.cpp code (the goal is to be simple and CPU-only, for now).

**Comment by husnoo** [comment]
Yeah it was the Facebook Demucs with pytorch. I'd prefer the cpp one but
the torch GPU version was about 37x faster, so I couldn't ignore it haha!
