### ISSUE TITLE
How to apply it in WebAssembly?

### ISSUE THREAD

**Issue by asasas234** [sevagh/demucs.cpp#20]
Hello, I would like to use this library through WebAssembly technology in the browser, but after looking at this library and the project https://github.com/sevagh/freemusicdemixer.com, I really don't understand how it is applied. Could you please provide some documentation or tutorials to guide me? Thank you very much.

**Comment by illbexyz** [comment]
From https://github.com/sevagh/freemusicdemixer.com 's docs it seems the library is supposed to be compiled using [emscripten](https://emscripten.org/). I gave it a shot but I wasn't able to compile it, but I'm not really familiar with this ecosystem. 

Adding instructions to the README would be very appreciated 🙂

**Comment by sevagh** [comment]
I'll work on adding more obvious WebAssembly pieces to this repo.

**Comment by sevagh** [comment]
Take a look at this: https://github.com/sevagh/demucs.cpp/tree/wasm/src_wasm

It gives some hints (not all) of how to make a functioning website similar to freemusicdemixer.com

**Comment by illbexyz** [comment]
The instructions are very clear. I was able to compile `demucs.js` and `demucs.wasm` correctly on MacOS. If it can be helpful to anyone else, I deviated from the instructions and installed `emscripten` on MacOS via `brew install emscripten`.

I'll try running the compiled files in the browser later, but I understand the required steps.

Thanks for the help and for your efforts in this amazing project 🙌🏻

**Comment by asasas234** [comment]
Thank you very much

**Comment by asasas234** [comment]
@illbexyz @sevagh Sorry to bother you, I always get the following error when trying wasm files. Can you all compile normally? Do I need to do anything extra?

```
/root/emsdk/upstream/lib/clang/19/include/mmintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"
   14 | #error "This header is only meant to be used on x86 and x64 architecture"
```

**Comment by illbexyz** [comment]
This command worked for me:

```bash
rm -rf build-wasm && mkdir -p build-wasm && cd build-wasm \
  && emcmake cmake -DCMAKE_BUILD_TYPE=Release \
  ../src_wasm && make -j16'
```

**Comment by asasas234** [comment]
@illbexyz Okay, I used the same command as you, but it didn't work... My system is M1 Max. I'm not sure if this has anything to do with the operating system.

**Comment by sevagh** [comment]
Are you sure you are using `emcmake cmake` and not plain `cmake`?

**Comment by asasas234** [comment]
> Are you sure you are using `emcmake cmake` and not plain `cmake`?

Yes, I am sure that I executed it with the following command.
```
rm -rf build-wasm && mkdir -p build-wasm && cd build-wasm \
  && emcmake cmake -DCMAKE_BUILD_TYPE=Release \
  ../src_wasm && make -j16
```

**Comment by sevagh** [comment]
I think it's OK to keep this issue closed. I think Mac/OSX problems with the Emscripten/WASM toolchain is out of the scope of demucs.cpp
