### ISSUE TITLE
Demucs weights

### ISSUE THREAD

**Issue by gitbearflying** [sevagh/demucs.cpp#22]
Hi,

I've successfully compiled demucs.cpp but have problems setting up the python environment.
Is there another way(link?) to download the demucs weights/models, to then convert these to ggml?

Thanks!

**Comment by gitbearflying** [comment]
I answer my own question:
After downloading about 10Gb in a micromamba env, i was able to download and convert the demucs model files, the links are

https://dl.fbaipublicfiles.com/demucs/hybrid_transformer/955717e8-8726e21a.th
https://dl.fbaipublicfiles.com/demucs/hybrid_transformer/5c90dfd2-34c22ccb.th
https://dl.fbaipublicfiles.com/demucs/hybrid_transformer/f7e0c4bc-ba3fe64a.th
https://dl.fbaipublicfiles.com/demucs/hybrid_transformer/d12395a8-e57c48e6.th
https://dl.fbaipublicfiles.com/demucs/hybrid_transformer/92cfc3b6-ef3bcb9c.th
https://dl.fbaipublicfiles.com/demucs/hybrid_transformer/04573f0d-f3cf25b2.th
https://dl.fbaipublicfiles.com/demucs/hybrid_transformer/75fc33f5-1941ce65.th

To convert, these need to be placed here: ~/.cache/torch/hub/checkpoints/

To save this hassle for everybody else, i uploaded the ggml files here:
https://huggingface.co/datasets/Retrobear/demucs.cpp/tree/main

Cheers

**Comment by sevagh** [comment]
Nice - did these instructions not work? https://github.com/sevagh/demucs.cpp?tab=readme-ov-file#convert-weights

I suppose they are Linux-centric (where `~/.cache/torch/hub/checkpoints` is where Torch automatically downloads the weights files). That step should run when the model is initialized like so:
https://github.com/sevagh/demucs.cpp/blob/main/scripts/convert-pth-to-ggml.py#L49-L70

When `demucs.pretrained.get_model` is called, it should automatically download those files to `Path(torch.hub.get_dir()) / "checkpoints"`.

**Comment by gitbearflying** [comment]
Yes, after all the instructions did work. I had to remove "-e ./vendor/demucs" from requirements.txt and manually install torch and demucs. I have an old slow machine and slow internet connections, various timeouts while downloading the whole python-env etc..
Indeed then the weight downloads and conversion did work flawlessly, i put the links here just for reference as i asked for them myself. Maybe these are useful(at least to me) if another conversion to something else is needed.

**Comment by sevagh** [comment]
Your huggingface model files might be useful to others, in case you want to add them to the README of this repo I'd be happy to accept a PR.

**Comment by gitbearflying** [comment]
> Your huggingface model files might be useful to others, in case you want to add them to the README of this repo I'd be happy to accept a PR.

Done :-)
