### ISSUE TITLE
Skipping crosstransformer

### ISSUE THREAD

**Issue by gaborszanto** [sevagh/demucs.cpp#24]
Thank you very much for this repo, I learned a lot!

Question: I'm trying to skip the crosstransformer as mentioned in model inference, but in that case I don't get an "audio" output, but mostly zeroes with an occasional 1 or -1. If I skip the upsampling and downsampling too, I get some audio-like garbage where some stems can be heard behind the noise. Did you successfully run this with skipping the crosstransformer?

**Comment by sevagh** [comment]
>I'm trying to skip the crosstransformer as mentioned in model inference,

Where is this mentioned? If the pretrained weights trained with the crosstransformer, I can't imagine skipping it will lead to good results.

I imagine there could be some weights out in the world that were trained without the crosstransformer (simple encoder/decoder). Demucs v3 is like that.

**Comment by gaborszanto** [comment]
[It's mentioned here](https://github.com/sevagh/demucs.cpp/blob/aeeb4fafb4f52321a7250ee8ecfcae56d929b985/src/model_inference.cpp#L264)

Thank you very much for the clarification.

**Comment by sevagh** [comment]
Oh - there I probably mean a skip connection.
