### ISSUE TITLE
CMakeLists.txt demucs.cpp.test target - missing dependency gtest

### ISSUE THREAD

**Issue by olilarkin** [sevagh/demucs.cpp#7]
demucs.cpp.test depends on googletest, which is not vendord or in the README.md. 
I can't build that target on macOS. Maybe if I install via homebrew, although I think it might be better to include it as a submodule?

**Comment by SuperKogito** [comment]
I had the same issue on linux (Ubuntu). This can be solved using `sudo apt-get install libgtest-dev`

**Comment by sevagh** [comment]
Gtest missing from the git submodules indeed goes counter to the rest of the vendoring strategy - I'll look into including it.
